---
title: Privacy Policy
date: "2024-12-2"
# date-modified: "2023-12-14"
# format:
#   html:
#     embed-resources: true
#     self-contained-math: true
toc: false
back-to-top-navigation: false
---

### Google Analytics

My website uses Google Analytics[^1] to collect data about your interactions with the site to better understand visitor behavior and improve content. Google Analytics collects data such as your IP address, browser type, device information, and pages visited on the site.

#### How I Use the Data:

- **Analytics**: I use the information to analyze website traffic and enhance user experience.
- **Customization**: To personalize content and features based on user preferences.
- **Performance**: To monitor and improve website functionality.

#### Data Sharing:

I do not sell or share personal data collected through Google Analytics with third parties except as required by law. Google may process data as described in their [Privacy Policy](https://policies.google.com/technologies/partner-sites).

#### Your Choices:

- **Opt-Out**: You can prevent data collection by Google Analytics by installing the [Google Analytics Opt-out Browser Add-on](https://tools.google.com/dlpage/gaoptout).
- **Cookies**: You can manage cookie preferences through your browser settings.

#### For More Information:

To learn more about how Google handles data, visit their [Data Protection Policies](https://support.google.com/analytics/answer/6004245). By using my website, you consent to the use of Google Analytics as outlined in this policy.

[^1]: I do plan on migrating to a more privacy-respecting analytics tool, such as [WP Statistics](https://wp-statistics.com/) in the future.