---
title: "Notes on Deep Learning for Coders"
subtitle: "What I Learned from Deep Learning for Coders with fastai & PyTorch"
date: "2023-05-01"
date-modified: "2023-05-10"
---

## Deep Learning Process

### Splitting

Before you begin setting up a deep learning network, make sure you split your dataset into three subsets: **training**, **validation**, and **testing**. The training set is used to fit the **parameters**[^1] (this is what we mean by *training* the model), the validation set is used to adjust the **hyperparameters**[^2] and to evaluate how well the model is generalizing (and not overfitting), and the testing set is used as a final measure of how well the model performs on an unseen data. This figure shows how the dataset should be splitted:

```{mermaid}
flowchart TB
    dataset[(Dataset)] --> train[(Training set)]
    dataset --> valid[(Validation set)]
    dataset --> test[(Testing set)]
```
<br>
The validation set is data that is hidden from the model, and the testing set is data that is hidden from human modelers (people who are adjusting the hyperparameters). We use the validation set to prevent the model from memorizing the training set instead of generalizing, and we use the testing set to prevent the human modelers from adjusting too much of the hyperparameters to fit the validation set rather than on unseen data that the model is supposed to perform on.

Note that depending on data availability, having a testing set may not always be possible. However, it is crucial to at least have a validation set.

### Training

These figures are my attempt to summarize a typical single epoch of training a deep learning model. Remember that *training* is a machine learning term for finding the most optimal parameters. Some processes may vary depending on the specific architecture and techniques used.

Figure 1 (Training set):

```{mermaid}
flowchart TB
    train[(Training set)]
    indep(Independent variable)
    depen(Dependent variable)
    arch{Architecture}
    param(Current parameters)
    newpa(Updated parameters)
    pred[(Prediction)]
    lossfn[[Loss function]]
    metric[[Metric function]]
    met(Accuracy)
    loss(Training loss)
    gdfn[[Backpropagation]]
    lr(Learning rate)
    gd(Gradient of parameters)
    step[[Gradient descent]]

    train --> indep
    train --> depen
    indep --> arch
    depen --> lossfn
    depen --> metric
    param --> arch
    arch --> pred
    pred --> lossfn
    pred --> metric
    metric --> met
    lossfn --> loss
    lossfn --> gdfn
    param --> gdfn
    gdfn --> gd
    gd --> step
    lr --> step
    step --> newpa
```
<br>
Figure 2 (Validation set):

```{mermaid}
flowchart TB
    valid[(Validation set)]
    param(Current parameters)
    indep(Independent variable)
    depen(Dependent variable)
    arch{Architecture}
    pred[(Prediction)]
    lossfn[[Loss function]]
    loss(Validation loss)

    valid --> indep
    valid --> depen
    indep --> arch
    param --> arch
    depen --> lossfn
    arch --> pred
    pred --> lossfn
    lossfn --> loss
```
<br>
An **architecture** is composed of an input layer, hidden layers, and an output layer. The function of the input layer is to receive the input data (**independent variable**) and pass it to the hidden layers. The function of the hidden layers is then to pick up on the patterns by extracting and combining different **features**[^3] of the input data (technically, of the previous layer) in an increasing level of generalization.

More specifically, each hidden layer is made up of **neurons**. These neurons produce outputs, known as **activations**. The activations are typically calculated by taking the dot product of the weights and the activations from the previous layer, adding a bias, and then passing the result through an **activation function**[^4].

Weights determine the amount of *influence* a neuron has on the activation of another neuron in the subsequent layer. Negative weights decrease the activation, while positive weights increase the activation. The *magnitude* of the weighted sum indicates the *significance* of the activation. Bias controls the *sensitivity* of the activation by setting a certain threshold for when the neuron will activate based on the weighted sum.

The output layer produces the model’s best guess based on the learned features (encoded as parameters in the hidden layers) from the input data in the training set. The output layer is also known as the **prediction**.

As a side note, we can use the principles of OOP to understand the difference between an architecture and a model. An architecture strictly refers to the structure of a neural network, including the number of neurons and layers, and how they are connected. It is like a class in OOP. A model, on the other hand, is an instance of an architecture that has been trained and has fitted parameters. In OOP terms, a model is like an object created from the architecture class.

**Accuracy**[^5] is a metric used to evaluate the performance of a model by measuring the percentage of correct predictions made by the model. It uses the training set’s label (independent variable) as the reference.

**Loss** is a function used to train a model by measuring the difference (also known as the error) between its predictions and the label. Conventionally, a high difference would indicate poor model performance, while a low difference would indicate good model performance. 

The goal of training a model is to minimize the **training loss** value, which is typically done through an optimization process that involves calculating the gradient (**backpropagation**) and using it to update the model’s parameters (**gradient descent**).

**Validation loss**, on the other hand, is value used for monitoring **overfitting**. Since it is not used to fit the model’s parameters, it provides a measure of the model’s performance on data it has not been trained on. Overfitting occurs when the model begins to memorize its training set rather than generalize. This is indicated by a decreasing training loss and an increasing validation loss.

[^1]: Weights and biases.

[^2]: Learning rate, number of neurons, number of layers, etc.

[^3]: Features are measurable characteristics or properties of the input data. Features can be as simple as individual pixel values of an image or as complex as an existence of a particular shape in the input data.

[^4]: Sigmoid, ReLU, Heaviside, Linear, etc.

[^5]: Note that accuracy is only used in classification models and not in regression models.